config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('myapps.core.urls', namespace='core')),
                  path('member/', include('myapps.member.urls', namespace='member')),
                  path('order/', include('myapps.order.urls', namespace='order')),
                  path('product/', include('myapps.product.urls', namespace='product')),
                  path('schema/', SpectacularAPIView.as_view(), name='schema'),
                  # Optional UI:
                  path('swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
                  path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
                  path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
                       name='password_reset_complete'),
                  path('api-auth/', include('rest_framework.urls')),

 #    jwt

                  path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh')

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('home/', views.Index.as_view(), name='index'),
    path('', views.Index.as_view(), name='index'),

    # path('index/', views.Index.as_view(), name='index'),
]

myapps/member/urls.py
from django.urls import path
from . import views
from django.urls import reverse, reverse_lazy

from django.contrib.auth.views import LogoutView


app_name = 'member'
urlpatterns = [
    path('loginpass/', views.LoginPassView.as_view(), name='loginpass'),
    path('loginpassapi/', views.LoginPassAPIView.as_view(), name='loginpassapi'),
    path('loginemail/', views.LoginEmailView.as_view(), name='loginemail'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('core:index')), name='logout'),
    path('singup/', views.SignUpView.as_view(), name='signup'),
    path('check_email/', views.ValidateEmailView.as_view(), name='check_email'),
    path('check_code/', views.ValidateCodeView.as_view(), name='check_code'),


#     reset password-------

]

myapps/order/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'order'
urlpatterns = [
    path('profile_drf/', views.ProfileApiView.as_view(), name='profile_drf'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('create_address/', views.CreateAddressView.as_view(), name='create_address'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('update_user/', views.UpdateUserView.as_view(), name='update_user'),
    path('check_code/', views.CheckCodeView.as_view(), name='check_code'),
    path('create_cart/', views.CreateCartView.as_view(), name='create_cart'),
    path('check_store/', views.CheckStoreView.as_view(), name='check_store'),
    path('show_address/', views.ShowAddressView.as_view(), name='show_address'),
    path('delete_address/<int:pk>/', views.DeleteAddresseView.as_view(), name='del_address'),
    path('payment/', TemplateView.as_view(template_name='order/payment.html')),
    path('back_store/', views.BackStoreView.as_view(), name='back_store'),
    path('activate/', views.ActivateView.as_view(), name='back_store'),
    path('code_activate/', views.CodeActivateView.as_view(), name='back_store'),
]

myapps/product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [


    path('category/', views.CategoryView.as_view(), name='category'),
path('products/<int:id>/', views.products_view, name='products'),
path('single_product/<int:pk>/', views.SingleProduct.as_view(), name='single_product'),
path('create_comment/<int:id>', views.CreateComment.as_view(), name='create_comment'),
path('reply_comment/<int:id_p>/<int:id_c>', views.CreateReplyComment.as_view(), name='reply_comment'),
    ]

templates/partiall/categoryy.html
{% for subsub in sub %}
 <li class="nav-item"><a class="nav-link " href="{% url 'product:products' subsub.id %}">    {{ subsub.title }}</a></li>
    {% if subsub.childrn %}
        {% include "core/partial/categoryy.html" with sub=subsub.childrn %}
    {% endif %}
{% endfor %}

templates/partiall/footer.html
<!-- ================ Subscribe section start ================= -->
  <section class="subscribe-position">
    <div class="container">
      <div class="subscribe text-center">
        <h3 class="subscribe__title">Get Update From Anywhere</h3>
        <p>Bearing Void gathering light light his eavening unto dont afraid</p>
        <div id="mc_embed_signup">
          <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe-form form-inline mt-5 pt-1">
            <div class="form-group ml-sm-auto">
              <input class="form-control mb-1" type="email" name="EMAIL" placeholder="Enter your email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '" >
              <div class="info"></div>
            </div>
            <button class="button button-subscribe mr-auto mb-1" type="submit">Subscribe Now</button>
            <div style="position: absolute; left: -5000px;">
              <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
            </div>

          </form>
        </div>
        
      </div>
    </div>
  </section>
	<!-- ================ Subscribe section end ================= -->		  


 
<!--================ Start footer Area  =================-->	
	<footer class="footer">
		<div class="footer-area">
			<div class="container">
				<div class="row section_gap">
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title large_title">Our Mission</h4>
							<p>
								So seed seed green that winged cattle in. Gathering thing made fly you're no 
								divided deep moved us lan Gathering thing us land years living.
							</p>
							<p>
								So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved 
							</p>
						</div>
					</div>
					<div class="offset-lg-1 col-lg-2 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Quick Links</h4>
							<ul class="list">
								<li><a href="#">Home</a></li>
								<li><a href="#">Shop</a></li>
								<li><a href="#">Blog</a></li>
								<li><a href="#">Product</a></li>
								<li><a href="#">Brand</a></li>
								<li><a href="#">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-6">
						<div class="single-footer-widget instafeed">
							<h4 class="footer_title">Gallery</h4>
							<ul class="list instafeed d-flex flex-wrap">

							</ul>
						</div>
					</div>
					<div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Contact Us</h4>
							<div class="ml-40">
								<p class="sm-head">
									<span class="fa fa-location-arrow"></span>
									Head Office
								</p>
								<p>123, Main Street, Your City</p>
	
								<p class="sm-head">
									<span class="fa fa-phone"></span>
									Phone Number
								</p>
								<p>
									+123 456 7890 <br>
									+123 456 7890
								</p>
	
								<p class="sm-head">
									<span class="fa fa-envelope"></span>
									Email
								</p>
								<p>
									free@infoexample.com <br>
									www.infoexample.com
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row d-flex">
					<p class="col-lg-12 footer-text text-center">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				</div>
			</div>
		</div>
	</footer>


    content -->
	<!--================ End footer Area  =================-->

templates/partiall/header.html
{% load static %}
<!--================ Start Header Menu Area =================-->

<header class="header_area">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand logo_h" href="index.html"><img src="img/logo.png" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto mr-auto ">
                    {% if user.is_authenticated %}

                        {% for group in user.groups.all %}

                            {% if group.name == "Administrators" or group.name == "controller" or group.name == "master_product"  or group.name == "operator"%}
                            <li class="nav-item mt-4">
                                <a href="admin/" class="button button-header"
                                >Addmin Panel</a>

                            </li>
                            {% endif %}
                        {% endfor %}
                        {% endif %}
                        <li class="nav-item active"><a class="nav-link" href={% url 'core:index' %}>Home</a></li>

                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">category</a>

                            <ul class="dropdown-menu">
                                {% for cat in categories %}

                                    <li class="nav-item"><a class="nav-link"
                                                            href="{% url 'product:products' cat.id %}">{{ cat.title }}</a>
                                    </li>
                                    {% if cat.childrn.exists %}
                                        {% include "./categoryy.html" with sub=cat.childrn %}
                                    {% endif %}
                                {% endfor %}

                            </ul>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item submenu dropdown">
                                <a href="{% url 'order:profile' %}" class="nav-link dropdown-toggle"
                                >My Panel</a>

                            </li>
                        {% endif %}
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Pages</a>
                            <ul class="dropdown-menu">
                                {% if not user.is_authenticated %}
                                    <li class="nav-item"><a class="nav-link" href="{% url "member:loginpass" %}">Login
                                        with password</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url "member:loginemail" %}">Login
                                        with email</a></li>
                                {% else %}
                                    <li id="logout" class="nav-item"><a class="nav-link" href="{% url "member:logout" %}">Logout</a>
                                    </li>
                                {% endif %}
                                <li class="nav-item"><a class="nav-link" href="{% url "member:signup" %}">Register New
                                    person</a></li>

                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
                    </ul>

                    <ul class="nav-shop">
                        <li class="nav-item">
                            <button><i class="ti-search"></i></button>
                        </li>
                        <li class="nav-item"><a href="{% url "order:cart" %}">
                            <button><i class="ti-shopping-cart"></i></button>
                        </a>+
                        </li>
                        <li class="nav-item"><a class="button button-header" href="{% url 'product:category' %}">Buy
                            Now</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>


{#     {% include './category.html' %}#}