config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('myapps.core.urls', namespace='core')),
                  path('member/', include('myapps.member.urls', namespace='member')),
                  path('order/', include('myapps.order.urls', namespace='order')),
                  path('product/', include('myapps.product.urls', namespace='product')),
                  path('schema/', SpectacularAPIView.as_view(), name='schema'),
                  # Optional UI:
                  path('swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
                  path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
                  path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
                       name='password_reset_complete'),
                  path('api-auth/', include('rest_framework.urls')),

 #    jwt

                  path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh')

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('home/', views.Index.as_view(), name='index'),
    path('', views.Index.as_view(), name='index'),

    # path('index/', views.Index.as_view(), name='index'),
]

myapps/product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [


    path('category/', views.CategoryView.as_view(), name='category'),
path('products/<int:id>/', views.products_view, name='products'),
path('single_product/<int:pk>/', views.SingleProduct.as_view(), name='single_product'),
path('create_comment/<int:id>', views.CreateComment.as_view(), name='create_comment'),
path('reply_comment/<int:id_p>/<int:id_c>', views.CreateReplyComment.as_view(), name='reply_comment'),
    ]

myapps/core/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from ..member.models import Status
from .manager import CustomBaseManager

import os


# Create your models here.
class Like(Status):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    objects=CustomBaseManager()

    def __str__(self):
        return f"{self.object_id}"
def get_image_path(instance, filename):
    if instance.content_type_id==7:
        return os.path.join('images','profile', filename)
    if instance.content_type_id==19:
        return os.path.join('images','product', filename)
    if instance.content_type_id==22:
        return os.path.join('images','category', filename)
    else:
        return os.path.join('images', 'other', filename)


class Image(Status):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    image = models.ImageField(upload_to=get_image_path)
    objects=CustomBaseManager()

    def __str__(self):
        return f"{self.object_id} {self.content_type}"

class Edites(Status):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    field_changed=models.CharField(max_length=100)
    old_value=models.CharField(max_length=100)
    objects=CustomBaseManager()

    def __str__(self):
        return f"{self.object_id}"

myapps/core/views.py
from datetime import timedelta
from django.core.cache import cache
from django.db.models import Count
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import ListView, View, CreateView, TemplateView, FormView, UpdateView
# Create your views here.
from ..product.models import *
from ..core.models import *
from django.core.paginator import Paginator
from django.core.cache import cache
from django.db.models import Subquery
class Index(View):
    paginate_by = 2
    def get(self, request):
        cache.clear()
        five_days_ago = timezone.now() - timedelta(days=5)
        newest = Product.objects.filter(created_at__gte=five_days_ago) # Replace with your actual queryset
        items_per_page = 2
        paginator = Paginator(newest, items_per_page)
        page_number = request.GET.get('page', 1)

        # Get the Page object for the current page
        page = paginator.get_page(page_number)

        # Pass the Page object to the template context
        context = {'newest': page}

        cheapest_detail=Detail.objects.filter(name='cost').order_by('value')[:30]

        best_like = Product.objects.filter(id__in=Like.objects.filter(content_type=ContentType.objects.get_for_model(Product)).values('object_id').annotate(num_likes=Count("object_id")).values("object_id"))
        # Like.objects.filter(content_type=ContentType.objects.get_for_model(Product)).values('object_id').annotate(num_likes=Count("object_id")).order_by("-num_likes")[:3]



         # context["best"]=
        context['cheapest']=cheapest_detail.values("detaill")
        context["categories"]=Category.objects.filter(parent=None)
        context["best_product"]=best_like
        context["images"]=Image.objects.filter(content_type=ContentType.objects.get_for_model(Detail))



        return render(request,"base.html",context)

myapps/core/templates/core/index.html
{% extends "base.html" %}
{% load cache %}
{% block content %}
  
 {% load static %}
<!--================ Start Header Menu Area =================-->
 <!--================ Hero banner start =================-->
    <section class="hero-banner">
      <div class="container">
        <div class="row no-gutters align-items-center pt-60px">
          <div class="col-5 d-none d-sm-block">
            <div class="hero-banner__img">
              <img class="img-fluid" src="{% static "img/home/hero-banner.png" %}" alt="">
            </div>
          </div>
          <div class="col-sm-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0">
            <div class="hero-banner__content">
              <h4>Shop is fun</h4>
              <h1>Browse Our Premium Product</h1>
              <p>Us which over of signs divide dominion deep fill bring they're meat beho upon own earth without morning over third. Their male dry. They are great appear whose land fly grass.</p>
              <a class="button button-hero" href="{% url 'product:category' %}"
              
              >Browse Now</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================ Hero banner end =================-->
    
     <section class="section-margin mt-0">
      <div class="owl-carousel owl-theme hero-carousel">
        <div class="hero-carousel__slide">
          <img src="{% static "img/home/hero-banner.png" %}" alt="" class="img-fluid">
          <a href="#" class="hero-carousel__slideOverlay">
            <h3>Wireless Headphone</h3>
            <p>Accessories Item</p>
          </a>
        </div>
        <div class="hero-carousel__slide">
          <img src="{% static "img/home/hero-banner.png" %}" alt="" class="img-fluid">
          <a href="#" class="hero-carousel__slideOverlay">
            <h3>Wireless Headphone</h3>
            <p>Accessories Item</p>
          </a>
        </div>
        <div class="hero-carousel__slide">
          <img src="{% static "img/home/hero-banner.png" %}" alt="" class="img-fluid">
          <a href="#" class="hero-carousel__slideOverlay">
            <h3>Wireless Headphone</h3>
            <p>Accessories Item</p>
          </a>
        </div>
          
      </div>
    </section>

     <!--================ pagination start =================-->
     <div class="col-xl-9 col-lg-8 col-md-7">
          <!-- Start Filter Bar -->
          <div class="filter-bar d-flex flex-wrap align-items-center">

          <!-- Start Best Seller -->
          <section class="lattest-product-area pb-40 category-list">
            <div class="row">
                {% for product in newest  %}
                      <div class="col-md-6 col-lg-4">
                        <div class="card text-center card-product">
                          <div class="card-product__img">
                               {% for image in images %}
                                        {% if image.object_id == product.base_group.first.id %}
                                            <img class="card-img" src="{{image.image.url}}" alt="" >
                                        {% endif %}
                                    {% endfor %}

                            <ul class="card-product__imgOverlay">
                              <li><button><i class="ti-search"></i></button></li>
                              <li><button><i class="ti-shopping-cart"></i></button></li>
                              <li><button><i class="ti-heart"></i></button></li>
                            </ul>
                          </div>
                          <div class="card-body">
                            <p>{{ product.title }}</p>
                            <h4 class="card-product__title"><a href="{% url 'product:single_product' product.id %}">{{ product.description|truncatechars:10 }}...</a></h4>
                            <p class="card-product__price">${% for price in cost %}{% if price.detaill.id == product.id  %}{{price.value}}{% endif %}{% endfor %}</p>
                          </div>
                        </div>
                      </div>
            {% endfor %}
            </div>
          </section>
          <!-- End Best Seller -->
        </div>
      </div>
    </div>
  </section>
	<!-- ================ category section end ================= -->
</div>
    </div>
    
    <div class="pagination justify-content-center ">
    <span class="step-links">
        {% if newest.has_previous %}
            <a class="button button-subscribe mr-auto mb-1" href="?page=1">« first</a>
            <a class="button button-subscribe mr-auto mb-1" href="?page={{ newest.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">Page {{ newest.number }} of {{ newest.paginator.num_pages }}.</span>
        {% if newest.has_next %}
            <a class="button button-subscribe mr-auto mb-1" href="?page={{ newest.next_page_number }}">next</a>
            <a class="button button-subscribe mr-auto mb-1" href="?page={{ newest.paginator.num_pages }}">last »</a>
        {% endif %}
    </span>
</div>




    <!-- Content you want to cache (e.g., sidebar) -->
    <div>Recent Posts</div>
    <ul>
        <li>Post 11</li>
        <li>Post 2</li>
        <!-- ... -->
    </ul>


{% endblock content %}